import { useState } from "react";
import {
  FileText, CheckCircle, Boxes, ClipboardList, IndianRupee,
  Zap, Target, Clock, ShieldCheck, Users, ArrowRight, X
} from "lucide-react";
import "./AppLayout.css";

function Welcome() {
  const [showHelp, setShowHelp] = useState(false);

  return (
    <div className="home-page">
      <div className="welcome-row">
        <div>
          <h1>Welcome back, Aditya! 👋</h1>
          <p>Here’s what’s happening with your FTTH automation platform today.</p>
        </div>
      </div>

      <section className="hero-card">
        <div>
          <h2><span>Airtel GenEx</span> — Automate. Optimize. Accelerate.</h2>
          <p>
            Airtel GenEx converts telecom planning inputs into structured BOQ,
            BOM, MWO, OSP/ODN and CAPEX-ready reports. Upload the design,
            validate the data, generate documents and export them instantly.
          </p>

          <div className="feature-strip">
            <Feature icon={<Zap />} title="AI-Powered" text="Automation" />
            <Feature icon={<Target />} title="High Accuracy" text="Validation" />
            <Feature icon={<Clock />} title="Faster" text="Turnaround" />
            <Feature icon={<ShieldCheck />} title="Reliable" text="Reports" />
          </div>
        </div>

        <div className="hero-brand-art">
          <img src="/airtel-logo.png" alt="Airtel Logo" />
          <h2>GEN<span>EX</span></h2>
          <p>Generate and Export Your Way</p>
        </div>
      </section>

      <section className="stats-grid">
        <Stat icon={<FileText />} title="Total Projects" value="0" />
        <Stat icon={<CheckCircle />} title="Total Files Generated" value="0" />
        <Stat icon={<ClipboardList />} title="Total BOQ Files" value="0" />
        <Stat icon={<Boxes />} title="Total BOM Files" value="0" />
        <Stat icon={<FileText />} title="Total MWO Files" value="0" />
        <Stat icon={<IndianRupee />} title="Total CAPEX Files" value="0" />
      </section>

      <section className="bottom-grid">
        <div className="info-card">
          <h2>How GenEx Works</h2>
          <Step n="1" title="Upload Design" text="Upload DWG, DXF, KMZ or Excel-based planning files." />
          <Step n="2" title="Data Processing" text="The system extracts, maps and validates network quantities." />
          <Step n="3" title="Document Generation" text="BOQ, BOM, MWO and CAPEX files are generated automatically." />
          <Step n="4" title="Review & Export" text="Verify output and download final submission-ready documents." />

          <button className="outline-btn" onClick={() => setShowHelp(true)}>
            Learn More <ArrowRight size={17} />
          </button>
        </div>

        <div className="info-card">
          <h2>Files Generated by Category</h2>
          <div className="donut-zero">0</div>
          <p className="center-text">Total Files</p>

          <ul className="legend">
            <li><span className="red-dot"></span> BOQ Files <b>0</b></li>
            <li><span className="blue-dot"></span> BOM Files <b>0</b></li>
            <li><span className="yellow-dot"></span> MWO Files <b>0</b></li>
            <li><span className="green-dot"></span> CAPEX Files <b>0</b></li>
          </ul>
        </div>

        <div className="info-card">
          <h2>User Summary</h2>
          <div className="user-main">
            <Users size={44} />
            <h1>0</h1>
            <p>Total Users</p>
          </div>

          <UserRow label="Planners" value="0" />
          <UserRow label="Design Engineers" value="0" />
          <UserRow label="Verifiers" value="0" />
          <UserRow label="Administrators" value="0" />
        </div>
      </section>

      {showHelp && (
        <div className="modal-overlay">
          <div className="help-modal">
            <button className="close-modal" onClick={() => setShowHelp(false)}>
              <X size={22} />
            </button>

            <h2>How to Use Airtel GenEx</h2>

            <ol>
              <li><b>Create or open a project:</b> Add project name, area, planner details and customer/building information.</li>
              <li><b>Upload design:</b> Upload DWG/DXF/KMZ/Excel design files from the Upload Design menu.</li>
              <li><b>Validate data:</b> Check missing quantities, wrong layers, incorrect OSP/ODN mapping and incomplete FTTH details.</li>
              <li><b>Generate reports:</b> Automatically generate BOQ, BOM, MWO, CAPEX tracker and validation report.</li>
              <li><b>Review and export:</b> Download final reports and submit them for business/team approval.</li>
            </ol>

            <button className="outline-btn" onClick={() => setShowHelp(false)}>
              Got it
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function Feature({ icon, title, text }) {
  return (
    <div className="feature-item">
      <div>{icon}</div>
      <p>{title}<br /><span>{text}</span></p>
    </div>
  );
}

function Stat({ icon, title, value }) {
  return (
    <div className="stat-card">
      <div className="stat-icon">{icon}</div>
      <p>{title}</p>
      <h2>{value}</h2>
      <span>↑ 0% vs last month</span>
    </div>
  );
}

function Step({ n, title, text }) {
  return (
    <div className="step">
      <b>{n}</b>
      <div>
        <h4>{title}</h4>
        <p>{text}</p>
      </div>
    </div>
  );
}

function UserRow({ label, value }) {
  return (
    <div className="user-row">
      <span>{label}</span>
      <b>{value}</b>
    </div>
  );
}

export default Welcome;